---
- hosts: all
  vars:
    - i3_use_gaps: false
    - i3_terminal: xfce4-terminal
    - i3_use_polybar: false
  remote_user: root
  tasks:
  - name: Install missing packages
    apt:
      pkg:
        - i3-wm
        - i3lock
        - i3status
        - zsh
        - neovim
        - apt-file
        - rofi
        - nodejs
        - nitrogen
      state: latest
      update_cache: yes
  - name: Install fonts and update font cache
    script: install_fonts.sh
    args:
      creates: /usr/share/fonts/truetype/robotomono
  - name: Set shell of user root to zsh
    user:
      name: root
      shell: /bin/zsh
  - name: Copy wallpaper
    copy:
      src: wallpaper.png
      dest: /usr/share/backgrounds/kali/kali-i3.png
  - name: Set wallpaper
    copy:
      src: nitrogen.cfg
      dest: "{{ansible_env.HOME}}/.config/nitrogen/bg-saved.cfg"
  roles:
     - ansible-xresources
     - ansible-i3
     - ansible-vim
     - ansible-xfce4-terminal
     - ansible-tmux
     - ansible-zsh
     - ansible-rofi
